#ifndef SPACETRADERS_SCHEMAS_SHIP_MODULE_ENUMS_TYPE_H_
#define SPACETRADERS_SCHEMAS_SHIP_MODULE_ENUMS_TYPE_H_
typedef enum {
  MODULE_TYPE_MINERAL_PROCESSOR_I,
  MODULE_TYPE_GAS_PROCESSOR_I,
  MODULE_TYPE_CARGO_HOLD_I,
  MODULE_TYPE_CARGO_HOLD_II,
  MODULE_TYPE_CARGO_HOLD_III,
  MODULE_TYPE_CREW_QUARTERS_I,
  MODULE_TYPE_ENVOY_QUARTERS_I,
  MODULE_TYPE_PASSENGER_CABIN_I,
  MODULE_TYPE_MICRO_REFINERY_I,
  MODULE_TYPE_ORE_REFINERY_I,
  MODULE_TYPE_FUEL_REFINERY_I,
  MODULE_TYPE_SCIENCE_LAB_I,
  MODULE_TYPE_JUMP_DRIVE_I,
  MODULE_TYPE_JUMP_DRIVE_II,
  MODULE_TYPE_JUMP_DRIVE_III,
  MODULE_TYPE_WARP_DRIVE_I,
  MODULE_TYPE_WARP_DRIVE_II,
  MODULE_TYPE_WARP_DRIVE_III,
  MODULE_TYPE_SHIELD_GENERATOR_I,
  MODULE_TYPE_SHIELD_GENERATOR_II
} st_ship_module_types_e;
#endif