#ifndef SPACETRADERS_SCHEMAS_ENUMS_STAR_TYPE_H_
#define SPACETRADERS_SCHEMAS_ENUMS_STAR_TYPE_H_
typedef enum {
  NEUTRON_STAR,
  RED_STAR,
  ORANGE_STAR,
  BLUE_STAR,
  YOUNG_STAR,
  WHITE_DWARF,
  BLACK_HOLE,
  HYPERGIANT,
  NEBULA,
  UNSTABLE
} STAR_TYPE;
#endif