#ifndef SPACETRADERS_SCHEMAS_ENUMS_STAR_TYPE_H_
#define SPACETRADERS_SCHEMAS_ENUMS_STAR_TYPE_H_
typedef enum {
  STAR_TYPE_NEUTRON_STAR,
  STAR_TYPE_RED_STAR,
  STAR_TYPE_ORANGE_STAR,
  STAR_TYPE_BLUE_STAR,
  STAR_TYPE_YOUNG_STAR,
  STAR_TYPE_WHITE_DWARF,
  STAR_TYPE_BLACK_HOLE,
  STAR_TYPE_HYPERGIANT,
  STAR_TYPE_NEBULA,
  STAR_TYPE_UNSTABLE
} st_star_types_e;
#endif