#ifndef SPACETRADERS_SCHEMAS_SHIP_ENGINE_ENUMS_TYPE_H_
#define SPACETRADERS_SCHEMAS_SHIP_ENGINE_ENUMS_TYPE_H_
typedef enum {
  ENGINE_TYPE_IMPULSE_DRIVE_I,
  ENGINE_TYPE_ION_DRIVE_I,
  ENGINE_TYPE_ION_DRIVE_II,
  ENGINE_TYPE_HYPER_DRIVE_I
} st_ship_engine_types_e;
#endif