#ifndef SPACETRADERS_SCHEMAS_SHIP_REACTOR_ENUMS_TYPE_H_
#define SPACETRADERS_SCHEMAS_SHIP_REACTOR_ENUMS_TYPE_H_
typedef enum {
  REACTOR_SOLAR_I,
  REACTOR_FUSION_I,
  REACTOR_FISSION_I,
  REACTOR_CHEMICAL_I,
  REACTOR_ANTIMATTER_I
} st_ship_reactor_types_t;
#endif