#ifndef SPACETRADERS_SCHEMAS_SHIP_REACTOR_ENUMS_TYPE_H_
#define SPACETRADERS_SCHEMAS_SHIP_REACTOR_ENUMS_TYPE_H_
typedef enum {
  REACTOR_TYPE_SOLAR_I,
  REACTOR_TYPE_FUSION_I,
  REACTOR_TYPE_FISSION_I,
  REACTOR_TYPE_CHEMICAL_I,
  REACTOR_TYPE_ANTIMATTER_I
} st_ship_reactor_types_e;
#endif