#ifndef SPACETRADERS_SCHEMAS_SHIP_MOUNT_ENUMS_DEPOSIT_H_
#define SPACETRADERS_SCHEMAS_SHIP_MOUNT_ENUMS_DEPOSIT_H_
typedef enum {
  MOUNT_DEPOSIT_QUARTZ_SAND = 1 << 0,
  MOUNT_DEPOSIT_SILICON_CRYSTALS = 1 << 1,
  MOUNT_DEPOSIT_PRECIOUS_STONES = 1 << 2,
  MOUNT_DEPOSIT_ICE_WATER = 1 << 3,
  MOUNT_DEPOSIT_AMMONIA_ICE = 1 << 4,
  MOUNT_DEPOSIT_IRON_ORE = 1 << 5,
  MOUNT_DEPOSIT_COPPER_ORE = 1 << 6,
  MOUNT_DEPOSIT_SILVER_ORE = 1 << 7,
  MOUNT_DEPOSIT_ALUMINUM_ORE = 1 << 8,
  MOUNT_DEPOSIT_GOLD_ORE = 1 << 9,
  MOUNT_DEPOSIT_PLATINUM_ORE = 1 << 10,
  MOUNT_DEPOSIT_DIAMONDS = 1 << 11,
  MOUNT_DEPOSIT_URANITE_ORE = 1 << 12,
  MOUNT_DEPOSIT_MERITIUM_ORE = 1 << 13
} st_ship_mount_deposit_types_e;
#endif