#ifndef SPACETRADERS_SCHEMAS_SHIP_MOUNT_ENUMS_MOUNT_H_
#define SPACETRADERS_SCHEMAS_SHIP_MOUNT_ENUMS_MOUNT_H_
typedef enum {
  MOUNT_TYPE_GAS_SIPHON_I,
  MOUNT_TYPE_GAS_SIPHON_II,
  MOUNT_TYPE_GAS_SIPHON_III,
  MOUNT_TYPE_SURVEYOR_I,
  MOUNT_TYPE_SURVEYOR_II,
  MOUNT_TYPE_SURVEYOR_III,
  MOUNT_TYPE_SENSOR_ARRAY_I,
  MOUNT_TYPE_SENSOR_ARRAY_II,
  MOUNT_TYPE_SENSOR_ARRAY_III,
  MOUNT_TYPE_MINING_LASER_I,
  MOUNT_TYPE_MINING_LASER_II,
  MOUNT_TYPE_MINING_LASER_III,
  MOUNT_TYPE_LASER_CANNON_I,
  MOUNT_TYPE_MISSILE_LAUNCHER_I,
  MOUNT_TYPE_TURRET_I
} st_ship_mount_types_e;
#endif