#ifndef SPACETRADERS_SCHEMAS_SHIP_FRAME_ENUMS_TYPE_H_
#define SPACETRADERS_SCHEMAS_SHIP_FRAME_ENUMS_TYPE_H_

typedef enum {
  FRAME_TYPE_PROBE,
  FRAME_TYPE_DRONE,
  FRAME_TYPE_INTERCEPTOR,
  FRAME_TYPE_RACER,
  FRAME_TYPE_FIGHTER,
  FRAME_TYPE_FRIGATE,
  FRAME_TYPE_SHUTTLE,
  FRAME_TYPE_EXPLORER,
  FRAME_TYPE_MINER,
  FRAME_TYPE_LIGHT_FREIGHTER,
  FRAME_TYPE_HEAVY_FREIGHTER,
  FRAME_TYPE_TRANSPORT,
  FRAME_TYPE_DESTROYER,
  FRAME_TYPE_CRUISER,
  FRAME_TYPE_CARRIER
} st_ship_frame_types_e;
#endif