#ifndef SPACETRADERS_SCHEMAS_SHIP_FRAME_ENUMS_TYPE_H_
#define SPACETRADERS_SCHEMAS_SHIP_FRAME_ENUMS_TYPE_H_

typedef enum {
  FRAME_PROBE,
  FRAME_DRONE,
  FRAME_INTERCEPTOR,
  FRAME_RACER,
  FRAME_FIGHTER,
  FRAME_FRIGATE,
  FRAME_SHUTTLE,
  FRAME_EXPLORER,
  FRAME_MINER,
  FRAME_LIGHT_FREIGHTER,
  FRAME_HEAVY_FREIGHTER,
  FRAME_TRANSPORT,
  FRAME_DESTROYER,
  FRAME_CRUISER,
  FRAME_CARRIER
} st_ship_frame_types_t;
#endif