#ifndef SPACETRADERS_SCHEMAS_SHIP_ROLE_H_
#define SPACETRADERS_SCHEMAS_SHIP_ROLE_H_
typedef enum {
  SHIP_ROLE_FABRICATOR,
  SHIP_ROLE_HARVESTER,
  SHIP_ROLE_HAULER,
  SHIP_ROLE_INTERCEPTOR,
  SHIP_ROLE_EXCAVATOR,
  SHIP_ROLE_TRANSPORT,
  SHIP_ROLE_REPAIR,
  SHIP_ROLE_SURVEYOR,
  SHIP_ROLE_COMMAND,
  SHIP_ROLE_CARRIER,
  SHIP_ROLE_PATROL,
  SHIP_ROLE_SATELLITE,
  SHIP_ROLE_EXPLORER,
  SHIP_ROLE_REFINERY
} st_ship_roles_e;
#endif