#ifndef SPACETRADERS_SCHEMAS_SHIP_ROLE_H_
#define SPACETRADERS_SCHEMAS_SHIP_ROLE_H_
typedef enum {
  FABRICATOR,
  HARVESTER,
  HAULER,
  INTERCEPTOR,
  EXCAVATOR,
  TRANSPORT,
  REPAIR,
  SURVEYOR,
  COMMAND,
  CARRIER,
  PATROL,
  SATELLITE,
  EXPLORER,
  REFINERY
} st_ship_roles_t;
#endif