//
// Created by meridiandawn on 1/4/24.
//

#ifndef SPACETRADERS_SCHEMAS_SHIP_TYPE_H_
#define SPACETRADERS_SCHEMAS_SHIP_TYPE_H_
typedef enum {
  SHIP_TYPE_PROBE,
  SHIP_TYPE_MINING_DRONE,
  SHIP_TYPE_SIPHON_DRONE,
  SHIP_TYPE_INTERCEPTOR,
  SHIP_TYPE_LIGHT_HAULER,
  SHIP_TYPE_COMMAND_FRIGATE,
  SHIP_TYPE_EXPLORER,
  SHIP_TYPE_HEAVY_FREIGHTER,
  SHIP_TYPE_LIGHT_SHUTTLE,
  SHIP_TYPE_ORE_HOUND,
  SHIP_TYPE_REFINING_FREIGHTER,
  SHIP_TYPE_SURVEYOR

} st_ship_types_e;
#endif  // SPACETRADERS_SCHEMAS_SHIP_TYPE_H_
