#ifndef SPACETRADERS_SCHEMAS_ENUMS_WAYPOINTS_TYPE_H_
#define SPACETRADERS_SCHEMAS_ENUMS_WAYPOINTS_TYPE_H_
typedef enum {
  PLANET,
  GAS_GIANT,
  MOON,
  ORBITAL_STATION,
  JUMP_GATE,
  ASTEROID_FIELD,
  ASTEROID,
  ENGINEERED_ASTEROID,
  ASTEROID_BASE,
  NEBULA,
  DEBRIS_FIELD,
  GRAVITY_WELL,
  ARTIFICIAL_GRAVITY_WELL,
  FUEL_STATION
} WAYPOINT_TYPE;
#endif