#ifndef SPACETRADERS_SCHEMAS_WAYPOINT_ENUMS_TYPE_H_
#define SPACETRADERS_SCHEMAS_WAYPOINT_ENUMS_TYPE_H_
typedef enum {
  WAYPOINT_TYPE_PLANET,
  WAYPOINT_TYPE_GAS_GIANT,
  WAYPOINT_TYPE_MOON,
  WAYPOINT_TYPE_ORBITAL_STATION,
  WAYPOINT_TYPE_JUMP_GATE,
  WAYPOINT_TYPE_ASTEROID_FIELD,
  WAYPOINT_TYPE_ASTEROID,
  WAYPOINT_TYPE_ENGINEERED_ASTEROID,
  WAYPOINT_TYPE_ASTEROID_BASE,
  WAYPOINT_TYPE_NEBULA,
  WAYPOINT_TYPE_DEBRIS_FIELD,
  WAYPOINT_TYPE_GRAVITY_WELL,
  WAYPOINT_TYPE_ARTIFICIAL_GRAVITY_WELL,
  WAYPOINT_TYPE_FUEL_STATION
} st_waypoint_types_e;
#endif