#ifndef SPACETRADERS_SCHEMAS_FACTION_ENUMS_SYMBOL_H_
#define SPACETRADERS_SCHEMAS_FACTION_ENUMS_SYMBOL_H_
typedef enum {
  FACTION_SYMBOL_COSMIC,
  FACTION_SYMBOL_VOID,
  FACTION_SYMBOL_GALACTIC,
  FACTION_SYMBOL_QUANTUM,
  FACTION_SYMBOL_DOMINION,
  FACTION_SYMBOL_ASTRO,
  FACTION_SYMBOL_CORSAIRS,
  FACTION_SYMBOL_OBSIDIAN,
  FACTION_SYMBOL_AEGIS,
  FACTION_SYMBOL_UNITED,
  FACTION_SYMBOL_SOLITARY,
  FACTION_SYMBOL_COBALT,
  FACTION_SYMBOL_OMEGA,
  FACTION_SYMBOL_ECHO,
  FACTION_SYMBOL_LORDS,
  FACTION_SYMBOL_CULT,
  FACTION_SYMBOL_ANCIENTS,
  FACTION_SYMBOL_SHADOW,
  FACTION_SYMBOL_ETHEREAL
} st_faction_symbols_e;
#endif