#ifndef SPACETRADERS_SCHEMAS_FACTION_ENUMS_SYMBOL_H_
#define SPACETRADERS_SCHEMAS_FACTION_ENUMS_SYMBOL_H_
typedef enum {
  COSMIC,
  VOID,
  GALACTIC,
  QUANTUM,
  DOMINION,
  ASTRO,
  CORSAIRS,
  OBSIDIAN,
  AEGIS,
  UNITED,
  SOLITARY,
  COBALT,
  OMEGA,
  ECHO,
  LORDS,
  CULT,
  ANCIENTS,
  SHADOW,
  ETHEREAL
} FACTION_SYMBOL;
#endif